[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
media3Common = "1.9.0"
recyclerview = "1.4.0"
coreAnimation = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core-animation = { group = "androidx.core", name = "core-animation", version.ref = "coreAnimation" }

[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }
android-application = { id = "com.android.application", version = "8.12.0" }